server.port=8081
spring.datasource.url=jdbc:mysql://customer-db:3306/customerservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
booking.service.url=http://booking-service:8080/